name: run-unit-test
on: [push]
jobs:
  run-unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: run unit test
        run: ./gradlew testDebugUnitTest